### ISSUE TITLE
Unable to change the default values

### ISSUE THREAD

**Issue by FredericAssemat** [chtipepere/woocommerceAtosPlugin#1]
Hello,

with woocommerce 2.3.7, i can't change the default values to configure the order with Atos options.
I must change the default values with mine, but the gateway don't work : i can't checkout :(

Thank you for help! :)

Fred

**Comment by chtipepere** [comment]
Hi,

You can try this fork: https://github.com/MBwebagency/woocommerceAtosPlugin
It seems to be compatible with woocommerce >= 2.3

If so, tell me, I'll update this repo to add more compatibility.

πR

**Comment by FredericAssemat** [comment]
Hi,

the fork works!
Thank you so much!

Regards

Fred

**Comment by chtipepere** [comment]
I'll merge the fork to increase compatibility up to 2.3.7.

**Comment by chtipepere** [comment]
The plugin has been updated.
A typo was preventing the edit of the merchant id, which has been fixed in the fork (I've only tested the plugin using the default value).
You can keep using the fork or go back to the original plugin.
Note that the plugin in wordpress directory has been updated accordingly (v1.1).

Thanks for your input.
πR
